begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|mojang
operator|.
name|minecraft
operator|.
name|model
package|;
end_package

begin_class
specifier|public
specifier|abstract
class|class
name|Model
block|{
specifier|public
specifier|static
specifier|final
name|String
name|HUMANOID
init|=
literal|"humanoid"
decl_stmt|;
specifier|public
name|float
name|attackOffset
decl_stmt|;
specifier|public
name|float
name|headOffset
decl_stmt|;
comment|/**      * Sets the model's various rotation angles. For bipeds, var1 and var2 are      * used for animating the movement of arms and legs, where var1 represents      * the time(so that arms and legs swing back and forth) and var2 represents      * how "far" arms and legs can swing at most.      */
specifier|public
name|void
name|render
parameter_list|(
name|float
name|var1
parameter_list|,
name|float
name|var2
parameter_list|,
name|float
name|var3
parameter_list|,
name|float
name|yawDegrees
parameter_list|,
name|float
name|pitchDegrees
parameter_list|,
name|float
name|scale
parameter_list|)
block|{
block|}
block|}
end_class

end_unit

