begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|mojang
operator|.
name|util
package|;
end_package

begin_class
specifier|public
specifier|final
class|class
name|Vertex
block|{
specifier|public
name|Vec3D
name|vector
decl_stmt|;
specifier|public
name|float
name|u
decl_stmt|;
specifier|public
name|float
name|v
decl_stmt|;
comment|/** 	 * Build a Vertex object with the vector coordinates and UV. 	 *  	 * @param x 	 * @param y 	 * @param z 	 * @param u 	 * @param v 	 */
specifier|public
name|Vertex
parameter_list|(
name|float
name|x
parameter_list|,
name|float
name|y
parameter_list|,
name|float
name|z
parameter_list|,
name|float
name|u
parameter_list|,
name|float
name|v
parameter_list|)
block|{
name|this
argument_list|(
operator|new
name|Vec3D
argument_list|(
name|x
argument_list|,
name|y
argument_list|,
name|z
argument_list|)
argument_list|,
name|u
argument_list|,
name|v
argument_list|)
expr_stmt|;
block|}
comment|/** 	 * Build a Vertex object with a prebuilt Vector3D object and UV. 	 *  	 * @param vector 	 * @param u 	 * @param v 	 */
specifier|private
name|Vertex
parameter_list|(
name|Vec3D
name|vector
parameter_list|,
name|float
name|u
parameter_list|,
name|float
name|v
parameter_list|)
block|{
name|this
operator|.
name|vector
operator|=
name|vector
expr_stmt|;
name|this
operator|.
name|u
operator|=
name|u
expr_stmt|;
name|this
operator|.
name|v
operator|=
name|v
expr_stmt|;
block|}
comment|/** 	 * Build a Vertex object with another Vertex object and UV. 	 *  	 * @param vertex 	 * @param u 	 * @param v 	 */
specifier|private
name|Vertex
parameter_list|(
name|Vertex
name|vertex
parameter_list|,
name|float
name|u
parameter_list|,
name|float
name|v
parameter_list|)
block|{
name|vector
operator|=
name|vertex
operator|.
name|vector
expr_stmt|;
name|this
operator|.
name|u
operator|=
name|u
expr_stmt|;
name|this
operator|.
name|v
operator|=
name|v
expr_stmt|;
block|}
comment|/** 	 * Build a Vertex object without specifying a coordinate set. 	 *  	 * @param u 	 * @param v 	 * @return Vertex 	 */
specifier|public
specifier|final
name|Vertex
name|create
parameter_list|(
name|float
name|u
parameter_list|,
name|float
name|v
parameter_list|)
block|{
return|return
operator|new
name|Vertex
argument_list|(
name|this
argument_list|,
name|u
argument_list|,
name|v
argument_list|)
return|;
block|}
block|}
end_class

end_unit

