begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|mojang
operator|.
name|minecraft
operator|.
name|render
package|;
end_package

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|ByteBuffer
import|;
end_import

begin_import
import|import
name|java
operator|.
name|nio
operator|.
name|IntBuffer
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|ARBFramebufferObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|EXTFramebufferObject
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|GL11
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|GL30
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|GLContext
import|;
end_import

begin_class
specifier|public
class|class
name|FBO
block|{
specifier|private
name|IntBuffer
name|texture_index
init|=
name|GLAllocation
operator|.
name|createDirectIntBuffer
argument_list|(
literal|3
argument_list|)
decl_stmt|;
specifier|private
name|IntBuffer
name|depth_stencil_index
init|=
name|GLAllocation
operator|.
name|createDirectIntBuffer
argument_list|(
literal|3
argument_list|)
decl_stmt|;
specifier|private
name|IntBuffer
name|fbo_index
init|=
name|GLAllocation
operator|.
name|createDirectIntBuffer
argument_list|(
literal|3
argument_list|)
decl_stmt|;
specifier|private
name|ByteBuffer
name|texture
init|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
literal|16777216
argument_list|)
decl_stmt|;
specifier|private
name|ByteBuffer
name|texture_small
init|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
literal|16777216
argument_list|)
decl_stmt|;
specifier|private
name|int
name|sx
decl_stmt|;
specifier|private
name|int
name|sy
decl_stmt|;
specifier|private
name|int
name|smx
decl_stmt|;
specifier|private
name|int
name|smy
decl_stmt|;
specifier|private
name|int
name|refl_res
init|=
literal|2
decl_stmt|;
specifier|private
name|int
name|anti_aliasing
init|=
literal|1
decl_stmt|;
specifier|private
name|int
name|maxResolution
decl_stmt|;
specifier|private
name|boolean
name|fboarb
init|=
literal|false
decl_stmt|;
specifier|private
name|boolean
name|fbocore
init|=
literal|true
decl_stmt|;
specifier|public
name|FBO
parameter_list|(
name|int
name|size_x
parameter_list|,
name|int
name|size_y
parameter_list|,
name|int
name|aa
parameter_list|)
block|{
name|anti_aliasing
operator|=
name|aa
expr_stmt|;
name|IntBuffer
name|maxsize
init|=
name|GLAllocation
operator|.
name|createDirectIntBuffer
argument_list|(
literal|16
argument_list|)
decl_stmt|;
name|GL11
operator|.
name|glGetInteger
argument_list|(
literal|3379
argument_list|,
name|maxsize
argument_list|)
expr_stmt|;
name|maxResolution
operator|=
name|maxsize
operator|.
name|get
argument_list|(
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|size_x
operator|*
name|anti_aliasing
operator|>=
name|maxResolution
condition|)
block|{
name|anti_aliasing
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|maxResolution
operator|/
name|size_x
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Anti aliasing reset to "
operator|+
name|anti_aliasing
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|size_y
operator|*
name|anti_aliasing
operator|>=
name|maxResolution
condition|)
block|{
name|anti_aliasing
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|maxResolution
operator|/
name|size_y
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Anti aliasing reset to "
operator|+
name|anti_aliasing
argument_list|)
expr_stmt|;
block|}
name|size_x
operator|*=
name|anti_aliasing
expr_stmt|;
name|size_y
operator|*=
name|anti_aliasing
expr_stmt|;
name|sx
operator|=
name|size_x
expr_stmt|;
name|sy
operator|=
name|size_y
expr_stmt|;
name|smx
operator|=
name|size_x
operator|/
name|refl_res
expr_stmt|;
name|smy
operator|=
name|size_y
operator|/
name|refl_res
expr_stmt|;
name|texture
operator|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
name|sx
operator|*
name|sy
operator|*
literal|16
argument_list|)
expr_stmt|;
name|texture_small
operator|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
name|smx
operator|*
name|smy
operator|*
literal|16
argument_list|)
expr_stmt|;
if|if
condition|(
name|fboarb
condition|)
block|{
name|fbocore
operator|=
literal|false
expr_stmt|;
block|}
if|if
condition|(
name|fbocore
condition|)
block|{
name|initcore
argument_list|()
expr_stmt|;
block|}
if|else if
condition|(
name|fboarb
condition|)
block|{
name|initarb
argument_list|()
expr_stmt|;
block|}
else|else
block|{
name|init
argument_list|()
expr_stmt|;
block|}
block|}
specifier|public
name|void
name|bind
parameter_list|(
name|int
name|index
parameter_list|)
block|{
if|if
condition|(
operator|!
name|fboarb
condition|)
block|{
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
name|index
argument_list|)
argument_list|)
expr_stmt|;
block|}
if|else if
condition|(
operator|!
name|fbocore
condition|)
block|{
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
name|index
argument_list|)
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
name|index
argument_list|)
argument_list|)
expr_stmt|;
block|}
name|GL11
operator|.
name|glPushAttrib
argument_list|(
literal|2048
argument_list|)
expr_stmt|;
if|if
condition|(
name|index
operator|==
literal|2
condition|)
block|{
name|GL11
operator|.
name|glViewport
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|GL11
operator|.
name|glViewport
argument_list|(
literal|0
argument_list|,
literal|0
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
block|}
name|GL11
operator|.
name|glClear
argument_list|(
literal|17664
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glPushMatrix
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|bind_texture
parameter_list|(
name|int
name|index
parameter_list|)
block|{
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
name|index
argument_list|)
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|init
parameter_list|()
block|{
if|if
condition|(
operator|!
name|GLContext
operator|.
name|getCapabilities
argument_list|()
operator|.
name|GL_EXT_framebuffer_object
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"No FBO Extension supported"
argument_list|)
throw|;
block|}
name|GL11
operator|.
name|glGenTextures
argument_list|(
name|texture_index
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glGenFramebuffersEXT
argument_list|(
name|fbo_index
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glGenRenderbuffersEXT
argument_list|(
name|depth_stencil_index
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferTexture2DEXT
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindRenderbufferEXT
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glRenderbufferStorageEXT
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferRenderbufferEXT
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferTexture2DEXT
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindRenderbufferEXT
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glRenderbufferStorageEXT
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferRenderbufferEXT
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture_small
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferTexture2DEXT
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glBindRenderbufferEXT
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glRenderbufferStorageEXT
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|)
expr_stmt|;
name|EXTFramebufferObject
operator|.
name|glFramebufferRenderbufferEXT
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|int
name|framebuffer
init|=
name|EXTFramebufferObject
operator|.
name|glCheckFramebufferStatusEXT
argument_list|(
literal|36160
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|framebuffer
condition|)
block|{
case|case
literal|36053
case|:
break|break;
case|case
literal|36054
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_EXT exception"
argument_list|)
throw|;
case|case
literal|36055
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_EXT exception"
argument_list|)
throw|;
case|case
literal|36057
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_EXT exception"
argument_list|)
throw|;
case|case
literal|36059
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_EXT exception"
argument_list|)
throw|;
case|case
literal|36058
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_FORMATS_EXT exception"
argument_list|)
throw|;
case|case
literal|36060
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_EXT exception"
argument_list|)
throw|;
case|case
literal|36056
case|:
default|default:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unexpected reply from glCheckFramebufferStatusEXT: "
operator|+
name|framebuffer
argument_list|)
throw|;
block|}
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|initarb
parameter_list|()
block|{
if|if
condition|(
operator|!
name|GLContext
operator|.
name|getCapabilities
argument_list|()
operator|.
name|GL_ARB_framebuffer_object
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Swapping to FBO EXT"
argument_list|)
expr_stmt|;
name|fboarb
operator|=
literal|false
expr_stmt|;
name|fbocore
operator|=
literal|false
expr_stmt|;
name|init
argument_list|()
expr_stmt|;
return|return;
block|}
name|GL11
operator|.
name|glGenTextures
argument_list|(
name|texture_index
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glGenFramebuffers
argument_list|(
name|fbo_index
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glGenRenderbuffers
argument_list|(
name|depth_stencil_index
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture_small
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|)
expr_stmt|;
name|ARBFramebufferObject
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|int
name|framebuffer
init|=
name|ARBFramebufferObject
operator|.
name|glCheckFramebufferStatus
argument_list|(
literal|36160
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|framebuffer
condition|)
block|{
case|case
literal|36053
case|:
break|break;
case|case
literal|36054
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT exception"
argument_list|)
throw|;
case|case
literal|36055
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT exception"
argument_list|)
throw|;
case|case
literal|36059
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER exception"
argument_list|)
throw|;
case|case
literal|36060
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER exception"
argument_list|)
throw|;
case|case
literal|36056
case|:
case|case
literal|36057
case|:
case|case
literal|36058
case|:
default|default:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unexpected reply from glCheckFramebufferStatus: "
operator|+
name|framebuffer
argument_list|)
throw|;
block|}
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
specifier|private
name|void
name|initcore
parameter_list|()
block|{
name|String
name|version
init|=
name|GL11
operator|.
name|glGetString
argument_list|(
literal|7938
argument_list|)
decl_stmt|;
if|if
condition|(
name|Integer
operator|.
name|valueOf
argument_list|(
name|version
operator|.
name|substring
argument_list|(
literal|0
argument_list|,
literal|1
argument_list|)
argument_list|)
operator|.
name|intValue
argument_list|()
operator|<
literal|3
condition|)
block|{
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Swapping to FBO ARB"
argument_list|)
expr_stmt|;
name|fboarb
operator|=
literal|true
expr_stmt|;
name|fbocore
operator|=
literal|false
expr_stmt|;
name|initarb
argument_list|()
expr_stmt|;
return|return;
block|}
name|GL11
operator|.
name|glGenTextures
argument_list|(
name|texture_index
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glGenFramebuffers
argument_list|(
name|fbo_index
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glGenRenderbuffers
argument_list|(
name|depth_stencil_index
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|0
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|sx
argument_list|,
name|sy
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|1
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10241
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10240
argument_list|,
literal|9729
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10242
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexParameteri
argument_list|(
literal|3553
argument_list|,
literal|10243
argument_list|,
literal|33648
argument_list|)
expr_stmt|;
name|GL11
operator|.
name|glTexImage2D
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|,
literal|32849
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|,
literal|0
argument_list|,
literal|6408
argument_list|,
literal|5125
argument_list|,
name|texture_small
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
name|fbo_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferTexture2D
argument_list|(
literal|36160
argument_list|,
literal|36064
argument_list|,
literal|3553
argument_list|,
name|texture_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glBindRenderbuffer
argument_list|(
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glRenderbufferStorage
argument_list|(
literal|36161
argument_list|,
literal|6402
argument_list|,
name|smx
argument_list|,
name|smy
argument_list|)
expr_stmt|;
name|GL30
operator|.
name|glFramebufferRenderbuffer
argument_list|(
literal|36160
argument_list|,
literal|36096
argument_list|,
literal|36161
argument_list|,
name|depth_stencil_index
operator|.
name|get
argument_list|(
literal|2
argument_list|)
argument_list|)
expr_stmt|;
name|int
name|framebuffer
init|=
name|GL30
operator|.
name|glCheckFramebufferStatus
argument_list|(
literal|36160
argument_list|)
decl_stmt|;
switch|switch
condition|(
name|framebuffer
condition|)
block|{
case|case
literal|36053
case|:
break|break;
case|case
literal|36054
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT exception"
argument_list|)
throw|;
case|case
literal|36055
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT exception"
argument_list|)
throw|;
case|case
literal|36059
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER exception"
argument_list|)
throw|;
case|case
literal|36060
case|:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"FrameBuffer: "
operator|+
name|fbo_index
operator|+
literal|", has caused a GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER exception"
argument_list|)
throw|;
case|case
literal|36056
case|:
case|case
literal|36057
case|:
case|case
literal|36058
case|:
default|default:
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"Unexpected reply from glCheckFramebufferStatus: "
operator|+
name|framebuffer
argument_list|)
throw|;
block|}
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|unbind
parameter_list|()
block|{
if|if
condition|(
operator|!
name|fboarb
condition|)
block|{
name|EXTFramebufferObject
operator|.
name|glBindFramebufferEXT
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
if|else if
condition|(
operator|!
name|fbocore
condition|)
block|{
name|ARBFramebufferObject
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|GL30
operator|.
name|glBindFramebuffer
argument_list|(
literal|36160
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
name|GL11
operator|.
name|glPopMatrix
argument_list|()
expr_stmt|;
name|GL11
operator|.
name|glPopAttrib
argument_list|()
expr_stmt|;
block|}
specifier|public
name|void
name|unbind_texture
parameter_list|()
block|{
name|GL11
operator|.
name|glBindTexture
argument_list|(
literal|3553
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
specifier|public
name|void
name|updateFBOsize
parameter_list|(
name|int
name|size_x
parameter_list|,
name|int
name|size_y
parameter_list|)
block|{
name|size_x
operator|*=
name|anti_aliasing
expr_stmt|;
name|size_y
operator|*=
name|anti_aliasing
expr_stmt|;
if|if
condition|(
name|sx
operator|!=
name|size_x
operator|&&
name|sy
operator|!=
name|size_y
condition|)
block|{
if|if
condition|(
name|size_x
operator|*
name|anti_aliasing
operator|>=
name|maxResolution
condition|)
block|{
name|anti_aliasing
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|maxResolution
operator|/
name|size_x
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Anti aliasing reset to "
operator|+
name|anti_aliasing
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|size_y
operator|*
name|anti_aliasing
operator|>=
name|maxResolution
condition|)
block|{
name|anti_aliasing
operator|=
operator|(
name|int
operator|)
name|Math
operator|.
name|floor
argument_list|(
name|maxResolution
operator|/
name|size_y
argument_list|)
expr_stmt|;
name|System
operator|.
name|out
operator|.
name|println
argument_list|(
literal|"Anti aliasing reset to "
operator|+
name|anti_aliasing
argument_list|)
expr_stmt|;
block|}
name|sx
operator|=
name|size_x
expr_stmt|;
name|sy
operator|=
name|size_y
expr_stmt|;
name|smx
operator|=
name|size_x
operator|/
name|refl_res
expr_stmt|;
name|smy
operator|=
name|size_y
operator|/
name|refl_res
expr_stmt|;
name|texture
operator|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
name|sx
operator|*
name|sy
operator|*
literal|16
argument_list|)
expr_stmt|;
name|texture_small
operator|=
name|GLAllocation
operator|.
name|createDirectByteBuffer
argument_list|(
name|smx
operator|*
name|smy
operator|*
literal|16
argument_list|)
expr_stmt|;
if|if
condition|(
name|fbocore
condition|)
block|{
name|initcore
argument_list|()
expr_stmt|;
block|}
if|else if
condition|(
name|fboarb
condition|)
block|{
name|initarb
argument_list|()
expr_stmt|;
block|}
else|else
block|{
name|init
argument_list|()
expr_stmt|;
block|}
block|}
block|}
block|}
end_class

end_unit

