begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|mojang
operator|.
name|minecraft
package|;
end_package

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|input
operator|.
name|Mouse
import|;
end_import

begin_import
import|import
name|org
operator|.
name|lwjgl
operator|.
name|opengl
operator|.
name|Display
import|;
end_import

begin_class
specifier|public
class|class
name|MouseHelper
block|{
comment|/**      * Grabs the mouse cursor it doesn't move and isn't seen.      */
specifier|public
name|void
name|grabMouseCursor
parameter_list|()
block|{
name|Mouse
operator|.
name|setGrabbed
argument_list|(
literal|true
argument_list|)
expr_stmt|;
block|}
comment|/**      * Ungrabs the mouse cursor so it can be moved and set it to the center of the screen      */
specifier|public
name|void
name|ungrabMouseCursor
parameter_list|()
block|{
name|Mouse
operator|.
name|setCursorPosition
argument_list|(
name|Display
operator|.
name|getWidth
argument_list|()
operator|/
literal|2
argument_list|,
name|Display
operator|.
name|getHeight
argument_list|()
operator|/
literal|2
argument_list|)
expr_stmt|;
name|Mouse
operator|.
name|setGrabbed
argument_list|(
literal|false
argument_list|)
expr_stmt|;
block|}
block|}
end_class

end_unit

