begin_unit|revision:1.0.0;language:Java;cregit-version:0.0.1
begin_package
package|package
name|com
operator|.
name|mojang
operator|.
name|minecraft
package|;
end_package

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|File
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|IOException
import|;
end_import

begin_import
import|import
name|java
operator|.
name|io
operator|.
name|InputStream
import|;
end_import

begin_import
import|import
name|java
operator|.
name|net
operator|.
name|URL
import|;
end_import

begin_class
specifier|public
class|class
name|ResourceDownloadThread
extends|extends
name|Thread
block|{
specifier|private
specifier|static
specifier|final
name|String
index|[]
name|resourceFiles
init|=
operator|new
name|String
index|[]
block|{
literal|"music/calm1.ogg"
block|,
literal|"music/calm2.ogg"
block|,
literal|"music/calm3.ogg"
block|,
literal|"newmusic/hal1.ogg"
block|,
literal|"newmusic/hal2.ogg"
block|,
literal|"newmusic/hal3.ogg"
block|,
literal|"newmusic/hal4.ogg"
block|,
literal|"newsound/step/grass1.ogg"
block|,
literal|"newsound/step/grass2.ogg"
block|,
literal|"newsound/step/grass3.ogg"
block|,
literal|"newsound/step/grass4.ogg"
block|,
literal|"newsound/step/gravel1.ogg"
block|,
literal|"newsound/step/gravel2.ogg"
block|,
literal|"newsound/step/gravel3.ogg"
block|,
literal|"newsound/step/gravel4.ogg"
block|,
literal|"newsound/step/stone1.ogg"
block|,
literal|"newsound/step/stone2.ogg"
block|,
literal|"newsound/step/stone3.ogg"
block|,
literal|"newsound/step/stone4.ogg"
block|,
literal|"newsound/step/wood1.ogg"
block|,
literal|"newsound/step/wood2.ogg"
block|,
literal|"newsound/step/wood3.ogg"
block|,
literal|"newsound/step/wood4.ogg"
block|,
literal|"newsound/step/cloth1.ogg"
block|,
literal|"newsound/step/cloth2.ogg"
block|,
literal|"newsound/step/cloth3.ogg"
block|,
literal|"newsound/step/cloth4.ogg"
block|,
literal|"newsound/step/sand1.ogg"
block|,
literal|"newsound/step/sand2.ogg"
block|,
literal|"newsound/step/sand3.ogg"
block|,
literal|"newsound/step/sand4.ogg"
block|,
literal|"newsound/step/snow1.ogg"
block|,
literal|"newsound/step/snow2.ogg"
block|,
literal|"newsound/step/snow3.ogg"
block|,
literal|"newsound/step/snow4.ogg"
block|,
literal|"sound3/dig/grass1.ogg"
block|,
literal|"sound3/dig/grass2.ogg"
block|,
literal|"sound3/dig/grass3.ogg"
block|,
literal|"sound3/dig/grass4.ogg"
block|,
literal|"sound3/dig/gravel1.ogg"
block|,
literal|"sound3/dig/gravel2.ogg"
block|,
literal|"sound3/dig/gravel3.ogg"
block|,
literal|"sound3/dig/gravel4.ogg"
block|,
literal|"sound3/dig/stone1.ogg"
block|,
literal|"sound3/dig/stone2.ogg"
block|,
literal|"sound3/dig/stone3.ogg"
block|,
literal|"sound3/dig/stone4.ogg"
block|,
literal|"sound3/dig/wood1.ogg"
block|,
literal|"sound3/dig/wood2.ogg"
block|,
literal|"sound3/dig/wood3.ogg"
block|,
literal|"sound3/dig/wood4.ogg"
block|,
literal|"sound3/dig/cloth1.ogg"
block|,
literal|"sound3/dig/cloth2.ogg"
block|,
literal|"sound3/dig/cloth3.ogg"
block|,
literal|"sound3/dig/cloth4.ogg"
block|,
literal|"sound3/dig/sand1.ogg"
block|,
literal|"sound3/dig/sand2.ogg"
block|,
literal|"sound3/dig/sand3.ogg"
block|,
literal|"sound3/dig/sand4.ogg"
block|,
literal|"sound3/dig/snow1.ogg"
block|,
literal|"sound3/dig/snow2.ogg"
block|,
literal|"sound3/dig/snow3.ogg"
block|,
literal|"sound3/dig/snow4.ogg"
block|,
literal|"sound3/random/glass1.ogg"
block|,
literal|"sound3/random/glass2.ogg"
block|,
literal|"sound3/random/glass3.ogg"
block|}
decl_stmt|;
specifier|private
specifier|final
name|File
name|dir
decl_stmt|;
specifier|private
specifier|final
name|Minecraft
name|minecraft
decl_stmt|;
specifier|private
name|boolean
name|finished
init|=
literal|false
decl_stmt|;
specifier|public
specifier|static
name|boolean
name|done
init|=
literal|false
decl_stmt|;
name|boolean
name|running
init|=
literal|false
decl_stmt|;
specifier|public
name|ResourceDownloadThread
parameter_list|(
name|File
name|minecraftFolder
parameter_list|,
name|Minecraft
name|minecraft
parameter_list|)
block|{
name|this
operator|.
name|minecraft
operator|=
name|minecraft
expr_stmt|;
name|setName
argument_list|(
literal|"Resource download thread"
argument_list|)
expr_stmt|;
name|setDaemon
argument_list|(
literal|true
argument_list|)
expr_stmt|;
name|dir
operator|=
operator|new
name|File
argument_list|(
name|minecraftFolder
argument_list|,
literal|"resources/"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|dir
operator|.
name|exists
argument_list|()
operator|&&
operator|!
name|dir
operator|.
name|mkdirs
argument_list|()
condition|)
block|{
throw|throw
operator|new
name|RuntimeException
argument_list|(
literal|"The working directory could not be created: "
operator|+
name|dir
argument_list|)
throw|;
block|}
block|}
specifier|public
name|boolean
name|isFinished
parameter_list|()
block|{
return|return
name|finished
return|;
block|}
annotation|@
name|Override
specifier|public
name|void
name|run
parameter_list|()
block|{
name|File
name|musicFolder
init|=
operator|new
name|File
argument_list|(
name|dir
argument_list|,
literal|"music"
argument_list|)
decl_stmt|;
name|File
name|stepsFolder
init|=
operator|new
name|File
argument_list|(
operator|new
name|File
argument_list|(
name|dir
argument_list|,
literal|"newsound"
argument_list|)
argument_list|,
literal|"step"
argument_list|)
decl_stmt|;
name|File
name|digFolder
init|=
operator|new
name|File
argument_list|(
operator|new
name|File
argument_list|(
name|dir
argument_list|,
literal|"sound3"
argument_list|)
argument_list|,
literal|"dig"
argument_list|)
decl_stmt|;
name|File
name|randomFolder
init|=
operator|new
name|File
argument_list|(
operator|new
name|File
argument_list|(
name|dir
argument_list|,
literal|"sound3"
argument_list|)
argument_list|,
literal|"random"
argument_list|)
decl_stmt|;
name|File
name|newMusicFolder
init|=
operator|new
name|File
argument_list|(
name|dir
argument_list|,
literal|"newmusic"
argument_list|)
decl_stmt|;
try|try
block|{
name|GameSettings
operator|.
name|PercentString
operator|=
literal|"5%"
expr_stmt|;
name|GameSettings
operator|.
name|StatusString
operator|=
literal|"Downloading music and sounds..."
expr_stmt|;
name|LogUtil
operator|.
name|logInfo
argument_list|(
literal|"Downloading music and sounds..."
argument_list|)
expr_stmt|;
name|int
name|percent
init|=
literal|5
decl_stmt|;
for|for
control|(
name|String
name|fileName
range|:
name|resourceFiles
control|)
block|{
if|if
condition|(
name|percent
operator|>=
literal|80
condition|)
block|{
name|percent
operator|=
literal|80
expr_stmt|;
block|}
name|percent
operator|+=
literal|3
expr_stmt|;
name|File
name|file
init|=
operator|new
name|File
argument_list|(
name|dir
argument_list|,
name|fileName
argument_list|)
decl_stmt|;
if|if
condition|(
operator|!
name|file
operator|.
name|exists
argument_list|()
condition|)
block|{
name|GameSettings
operator|.
name|PercentString
operator|=
name|percent
operator|+
literal|"%"
expr_stmt|;
name|GameSettings
operator|.
name|StatusString
operator|=
literal|"Downloading https://s3.amazonaws.com/MinecraftResources/"
operator|+
name|fileName
operator|+
literal|"..."
expr_stmt|;
name|LogUtil
operator|.
name|logInfo
argument_list|(
literal|"Downloading https://s3.amazonaws.com/MinecraftResources/"
operator|+
name|fileName
argument_list|)
expr_stmt|;
name|URL
name|url
init|=
operator|new
name|URL
argument_list|(
literal|"https://s3.amazonaws.com/MinecraftResources/"
operator|+
name|fileName
argument_list|)
decl_stmt|;
try|try
init|(
name|InputStream
name|is
init|=
name|url
operator|.
name|openStream
argument_list|()
init|)
block|{
name|StreamingUtil
operator|.
name|copyStreamToFile
argument_list|(
name|is
argument_list|,
name|file
argument_list|)
expr_stmt|;
block|}
name|GameSettings
operator|.
name|StatusString
operator|=
literal|"Downloaded https://s3.amazonaws.com/MinecraftResources/"
operator|+
name|fileName
operator|+
literal|"!"
expr_stmt|;
name|LogUtil
operator|.
name|logInfo
argument_list|(
literal|"Downloaded https://s3.amazonaws.com/MinecraftResources/"
operator|+
name|fileName
argument_list|)
expr_stmt|;
block|}
block|}
name|GameSettings
operator|.
name|PercentString
operator|=
literal|"85%"
expr_stmt|;
name|GameSettings
operator|.
name|StatusString
operator|=
literal|"Downloaded music and sounds!"
expr_stmt|;
name|LogUtil
operator|.
name|logInfo
argument_list|(
literal|"Done downloading music and sounds!"
argument_list|)
expr_stmt|;
name|GameSettings
operator|.
name|StatusString
operator|=
literal|""
expr_stmt|;
name|GameSettings
operator|.
name|PercentString
operator|=
literal|""
expr_stmt|;
name|done
operator|=
literal|true
expr_stmt|;
block|}
catch|catch
parameter_list|(
name|Exception
name|ex
parameter_list|)
block|{
name|LogUtil
operator|.
name|logError
argument_list|(
literal|"Error downloading music and sounds!"
argument_list|,
name|ex
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|int
name|i
init|=
literal|1
init|;
name|i
operator|<=
literal|3
condition|;
name|i
operator|++
control|)
block|{
name|minecraft
operator|.
name|sound
operator|.
name|registerMusic
argument_list|(
literal|"calm"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|,
operator|new
name|File
argument_list|(
name|musicFolder
argument_list|,
literal|"calm"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|randomFolder
argument_list|,
literal|"glass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"random/glass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
block|}
for|for
control|(
name|int
name|i
init|=
literal|1
init|;
name|i
operator|<=
literal|4
condition|;
name|i
operator|++
control|)
block|{
name|minecraft
operator|.
name|sound
operator|.
name|registerMusic
argument_list|(
literal|"calm"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|,
operator|new
name|File
argument_list|(
name|newMusicFolder
argument_list|,
literal|"hal"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"grass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/grass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"gravel"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/gravel"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"stone"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/stone"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"wood"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/wood"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"cloth"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/cloth"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"sand"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/sand"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|stepsFolder
argument_list|,
literal|"snow"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"step/snow"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"grass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/grass"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"gravel"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/gravel"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"stone"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/stone"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"wood"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/wood"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"cloth"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/cloth"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"sand"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/sand"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
name|minecraft
operator|.
name|sound
operator|.
name|registerSound
argument_list|(
operator|new
name|File
argument_list|(
name|digFolder
argument_list|,
literal|"snow"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
argument_list|,
literal|"dig/snow"
operator|+
name|i
operator|+
literal|".ogg"
argument_list|)
expr_stmt|;
block|}
name|finished
operator|=
literal|true
expr_stmt|;
block|}
block|}
end_class

end_unit

